name: Build MSI on Release

on:
  release:
    types: [ created ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21
          java-package: 'jdk+fx'

      - uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install wixtoolset --version=3.11.2 --yes --no-progress

      - run: mvn -B clean package

      - shell: pwsh
        run: |
          jpackage `
            --name GZAssist `
            --app-version ${{ github.event.release.tag_name }} `
            --type msi `
            --input target `
            --main-jar GZAssist.jar `
            --main-class br.com.gzlabs.gzassist.Main `
            --icon src\main\resources\br\com\gzlabs\gzassist\presentation\favicon.ico `
            --dest target\dist `
            --win-shortcut `
            --win-menu `
            --win-dir-chooser `
            --win-menu-group "GZLabs" `
            --win-per-user-install

      - uses: softprops/action-gh-release@v2
        with:
          files: target/dist/*.msi
